### ISSUE TITLE
Creating the SeeMembers Component 

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#109]
# Creating the SeeMembers Component 🚀

## Overview
Hello Contributors! 🌟 We're thrilled to introduce a new component, 'SeeMembers,' to enhance the user experience in Hitch. This component will allow users to seamlessly view and interact with the members of a workspace. The design details are provided in Figma, ensuring a consistent and visually appealing integration.

## Tasks
1. **Integration:**
   Transform the 'SeeMembers' component design from Figma into a functional and aesthetically pleasing React component.

2. **User-Friendly Interface:**
   Craft an interface that allows users to easily navigate and interact with the list of members within a workspace.

## Design Details
Figma Link: [SeeMembers Figma Design](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=3zROxDSu7a4A8eqx-0)
<img width="576" alt="image" src="https://github.com/opencodeiiita/Hitch-Frontend/assets/120705327/2e029cfc-41ad-4eac-a3eb-fc34c2bf84bb">

## Considerations
- **Consistent Design Language:**
  Ensure that the 'SeeMembers' component aligns seamlessly with Hitch's overall design language.

- **Responsive Design:**
  Develop a component that adapts gracefully to various screen sizes, providing a seamless user experience.

## Timeframe
72 crafting hours.

Contributors, let's come together to build the 'SeeMembers' component and enhance the collaborative spirit of Hitch! Your coding expertise will play a crucial role in creating a visually appealing and user-friendly feature.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by WadadParker** [comment]
Claim

**Comment by WadadParker** [comment]
@akshayw1 can you assign me the create channel modal issue and unassign me this? 
I want to do harder issue

**Comment by akshayw1** [comment]
@WadadParker This is more harder I feel, That modal are subset of this issues

**Comment by TheDivineAurora** [comment]
claim

**Comment by Rohit-110** [comment]
@akshayw1  claim

**Comment by akshayw1** [comment]
@TheDivineAurora  You have already issue assigned, Please complete it before other claims.

**Comment by chiragmalik2612** [comment]
@akshayw1 two issues assigned to @TheDivineAurora (#109 and #107) assign me any
