### ISSUE TITLE
Creating the Right SideDrawer Feature 🚀

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#110]
# Creating the Right SideDrawer (Switchable)  🚀

## Overview
Hey Contributors! 🌟 We're excited to introduce a new feature in Hitch – the Right SideDrawer Toggle. This functionality will empower users to toggle the visibility of the Right SideDrawer, enhancing the flexibility and customization of their workspace. Let's collaborate to bring this dynamic feature to life!

[Figma Link](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=3zROxDSu7a4A8eqx-0)

## Tasks
1. **Implementation:**
   Develop the logic and UI components necessary to toggle the Right SideDrawer's visibility seamlessly.

2. **User Interaction:**
   Ensure a user-friendly experience by allowing users to easily show or hide the Right SideDrawer as needed.

## Considerations
- **Smooth Transition:**
  Implement a smooth transition effect when toggling the Right SideDrawer for a polished user experience.

- **Accessibility:**
  Ensure that the toggle functionality is accessible and intuitive for all users.

## Timeframe
48 crafting hours.

Contributors, let's make the Hitch workspace even more customizable with the addition of the Right SideDrawer Toggle! Your coding prowess will be crucial in creating a seamless and enjoyable user experience.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by ShauryaJain03** [comment]
Claim

**Comment by akshayw1** [comment]
@ShauryaJain03 , Please note. to use TailwindCss, MUI or Ant design on your flexiblity.

**Comment by akshayw1** [comment]
@ShauryaJain03  Please Update on the assigned issue

**Comment by TheDivineAurora** [comment]
Claim
