### ISSUE TITLE
Adding Reaction to Message Feature on Conversation Card 🚀📩

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#112]
# Adding Reaction to Message Feature on Conversation Card 🚀📩

## Overview
Hello Contributors! 🌟 We're excited to introduce a new feature to elevate communication within Hitch – the Reaction to Message on Conversation Card. This enhancement will allow users to react to messages, adding a dynamic and expressive element to the conversation. Let's collaborate to make Hitch's communication experience even more engaging!

## Tasks
1. **Implementation:**
   Integrate the Reaction to Message feature on Conversation Cards, enabling users to react to individual messages within a conversation.

2. **User Interface:**
   Design an intuitive and visually appealing interface for users to select and view reactions on messages.

## Considerations
- **Expressive Reactions:**
  Implement a variety of expressive reactions that users can choose from to react to messages.

[Figma Link 
](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=3zROxDSu7a4A8eqx-0)
## Timeframe
72 crafting hours.

Contributors, let's add a touch of expressiveness to Hitch's communication with the Reaction to Message feature! Your coding expertise will play a crucial role in creating a more engaging and dynamic conversation experience.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by LifeAsDev** [comment]
claim

**Comment by chiragmalik2612** [comment]
@akshayw1 two issues (#111  and #112 ) assigned to @LifeAsDev,  please assign me any
