### ISSUE TITLE
Crafting People and Member Cards 🌐👤

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#113]
# Crafting People and Member Cards 🌐👤

## Overview
Hello Contributors! 🚀 We're thrilled to introduce a visually engaging component to Hitch – People and Member Cards. These cards will be a central part of the user interface, providing a dynamic and attractive representation of community members. The Figma designs have been provided, making it easier for you to contribute. Let's collaborate to bring these cards to life and enhance the overall aesthetics of Hitch!

## Tasks
1. **Card Implementation:**
   Integrate the People and Member Card designs from Figma into functional React components, ensuring a seamless and visually appealing display.

2. **Dynamic Content:**
   Implement dynamic content rendering on the cards, showcasing relevant details such as user names, profile pictures, roles, or any other pertinent information.

## Figma Designs
[Figma Designs - People and Member Cards](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=622-586&mode=design&t=3zROxDSu7a4A8eqx-0)

<img width="515" alt="image" src="https://github.com/opencodeiiita/Hitch-Frontend/assets/120705327/e1db2456-cc02-41bd-a71c-88739ade9331">

## Considerations
- **Responsive Design:**
  Ensure that the People and Member Cards adapt gracefully to various screen sizes, providing a consistent and engaging user experience.

- **Interactive Elements:**
  Include interactive elements on the cards for users to explore profiles, initiate conversations, or perform other relevant actions.

## Timeframe
48 crafting hours.

Contributors, let's come together to craft visually appealing People and Member Cards for Hitch! Your coding expertise will play a crucial role in enhancing the overall aesthetics of our community space.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by Rohit-110** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by akshayw1** [comment]
@Rohit-110  Update

**Comment by Mannxxx** [comment]
Claim

**Comment by akshayw1** [comment]
@Mannxxx ,You can claim the issue #110
