### ISSUE TITLE
Designing and Implementing Create Channel Modals 🌐🔧

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#114]
# Designing and Implementing Channel Modals 🌐🔧

## Overview
Hello Contributors! 🚀 We're excited to introduce a streamlined way to create channels within Hitch – the Create Channel Modals. These modals will provide a user-friendly interface for users to efficiently create new channels in their workspaces. Figma designs have been provided, making it easier for you to contribute. Let's collaborate to design and implement these modals, enhancing the overall channel management experience in Hitch!

## Tasks
1. **Modal Design:**
   Implement the provided Figma designs into visually appealing Create Channel Modals, considering a clean and intuitive layout for users to input channel details.

2. **Modal Implementation:**
   Integrate the modal designs into functional React components, ensuring a smooth and user-friendly channel creation process.

## Figma Designs
[Figma Designs - Create Channel Modals](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=3zROxDSu7a4A8eqx-0)

<img width="838" alt="image" src="https://github.com/opencodeiiita/Hitch-Frontend/assets/120705327/1f116de4-8d88-46f0-8075-3f8884583b7e">

2 AddChannelModals
1 AddPeopleModal

## Considerations
- **Input Validation:**
  Implement validation checks within the modals to ensure users provide necessary and valid information when creating a new channel.

- **User Guidance:**
  Include informative tooltips or guidance within the modals to assist users in understanding the channel creation process.

## Timeframe
48 crafting hours.

Contributors, let's come together to craft efficient and visually appealing Create Channel Modals for Hitch! Your expertise will play a crucial role in enhancing the channel management experience within our collaborative workspace.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by WadadParker** [comment]
Claim

**Comment by Rohit-110** [comment]
Claim

**Comment by WadadParker** [comment]
@akshayw1 Can you assign me this issue and unassign me from the other issue please?

I want to do harder issue

**Comment by Rohit-110** [comment]
@akshayw1  please assign me this issue

**Comment by akshayw1** [comment]
@Rohit-110 Check out the SeeMemberCard Issue, Its open for claims
