### ISSUE TITLE
Making the Workspace Dashboard Responsive 🌐📲

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#119]
# Making the Workspace Dashboard Responsive 🌐📲

## Overview
Hello Contributors! 🚀 Let's take our workspace dashboard in Hitch to the next level by making it responsive. The dashboard is already in place, and now we need your expertise to ensure it looks fantastic and functions seamlessly on various devices, from desktops to mobiles. Your contribution to making the workspace dashboard responsive is key to providing an excellent user experience.

## Tasks
1. **Responsive Design:**
   Apply responsive design principles to the existing workspace dashboard, ensuring it adapts flawlessly to different screen sizes and devices.

2. **Mobile Optimization:**
   Optimize the dashboard for mobile devices, making navigation and interaction smooth and intuitive.

## Timeframe
48 crafting hours.

Contributors, let's collaborate to make the workspace dashboard in Hitch responsive! Your expertise will play a crucial role in delivering a seamless experience across a variety of devices.

Thank you for contributing to the evolution of Hitch! 🌐🚀

**Comment by chiragmalik2612** [comment]
c

**Comment by WadadParker** [comment]
Claim

**Comment by WadadParker** [comment]
I had originally made the dashboard skeleton. So I know how to make the existing dashboard responsive. @akshayw1

**Comment by akshayw1** [comment]
If you want to discuss design, Please come over discord

**Comment by Mannxxx** [comment]
Claim
