### ISSUE TITLE
 Creating Huddle Component with Tailwind CSS 

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#129]
# Creating Huddle Component with Tailwind CSS 🚀🎙️🎥

## Overview
Hello Hitch Developers! 🌟 Let's embark on an exciting journey to create the Huddle component, incorporating both video and audio features for seamless communication within channels. This issue involves frontend implementation using Tailwind CSS to ensure a visually appealing and responsive design.

## Figma Design
 [Figma Design for component](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=HkmqjzMcbH4qohQv-0)
## Tasks
1. **Huddle Component Design:**
   Craft the visual design for the Huddle component, including elements for video and audio communication.

2. **Tailwind CSS Implementation:**
   Integrate Tailwind CSS to style the Huddle component, ensuring a clean and modern look.

3. **Video and Audio Features:**
   Implement frontend functionality for video and audio communication within the Huddle component.

## Considerations
- Optimize the design for responsiveness across various devices.
- Ensure a user-friendly interface with intuitive controls for video and audio features.
<img width="626" alt="image" src="https://github.com/opencodeiiita/Hitch-Frontend/assets/120705327/ee24b014-3b48-4299-84fc-502ae14b4ef2">

## Timeframe
48 crafting hours.

Hitch Developers, let's join forces to bring the Huddle component to life! Your creativity and expertise in Tailwind CSS will play a key role in enhancing the collaborative experience on Hitch.

Thank you for your dedication to the evolution of Hitch! 🚀🎤📹

**Comment by rnavaneeth992** [comment]
Claim

**Comment by WadadParker** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim
