### ISSUE TITLE
Creating Huddle Sidebar Components with Tailwind CSS 

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#130]
# Creating Huddle Sidebar Components with Tailwind CSS 🚀🎙️🎥

## Overview
Hello Hitch Developers! 🌟 Let's enhance the Huddle experience by creating both the Off-call and On-call Sidebar components. These sidebars complement the Huddle component, providing additional features when users are off-call and enhancing the experience during an ongoing Huddle call. The frontend implementation will utilize Tailwind CSS for a visually appealing and functional design.

### Huddle Off-call Sidebar
1. **Off-call Sidebar Design:**
   Craft the visual design for the Huddle Off-call Sidebar component, incorporating relevant features.

2. **Tailwind CSS Implementation:**
   Integrate Tailwind CSS to style the Off-call Sidebar, maintaining consistency with the overall design language.

### Huddle On-call Sidebar
1. **On-call Sidebar Design:**
   Craft the visual design for the Huddle On-call Sidebar component, incorporating relevant features.

2. **Tailwind CSS Implementation:**
   Integrate Tailwind CSS to style the On-call Sidebar, ensuring a seamless and visually pleasing interface.

<img width="346" alt="image" src="https://github.com/opencodeiiita/Hitch-Frontend/assets/120705327/6c72c127-eb5f-4630-9ce5-8a6b2467dfd4">

## Considerations
- Optimize the design for responsiveness across various devices.
- Ensure a cohesive and intuitive user interface.
- Implement interactive elements in the On-call Sidebar for an enhanced on-call experience.

## Timeframe
48 crafting hours.

Hitch Developers, let's create these essential sidebar components! Your expertise in Tailwind CSS will contribute to a polished and user-friendly interface on Hitch.

Thank you for your dedication to the evolution of Hitch! 🚀🌐

**Comment by kushal7201** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by Rohit-110** [comment]
claim
