### ISSUE TITLE
Lifting Off: Call-To-Action Section 

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/Hitch-Frontend#14]
**Call-To-Action Section** 

We've got a thrilling task for you – bring Hitch's vision to life by crafting the front end for the _Call-To-Action_ (CTA) section. Detailed instructions are provided below.

**Task Details:** 

#Design to Extreme

Your goal is to make a CTA section below the landing page of the Hitch. the respective Figma Design is provided below. 

**#KeyPoints**

- Ensure the CTA section looks amazing on all devices. We want a seamless experience for everyone.
- Feel free to enhance the layout as needed, aligning with the provided design
- Utilize the styling tech trio – Material-UI, Ant-Design, and TailwindCSS. 

#Time: 36 hours 

**#Link to Design**
[https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch-Admins?type=design&node-id=4-836&mode=design&t=dradGPlYh0B6Nkjp-0](url)

> NOTE: The work should be done in the new route, create folder home/cta.jsx in the app root folder, and start working on it.

comment to claim the issue.

**Comment by WadadParker** [comment]
claim

**Comment by akshayw1** [comment]
Make sure it should be responsive, The Design will be updated in figma

**Comment by Xaverick** [comment]
claim
