### ISSUE TITLE
Elevating the Footer Section!

### ISSUE THREAD

**Issue by shashankpatil28** [opencodeiiita/Hitch-Frontend#19]
### **Hey! We have a cool task for you – let's make Hitch's website look nice by working on the Footer section. All the details are below!**

**#Key Consideration**s:

1. Universal Appeal:
- Ensure the Footer's functionality seamlessly resonates across all devices.

2. Layout Enhancement:
- You can refine the layout to align with the provided design, elevating its visual impact.

3. Technological Proficiency:
- Employ the styling technologies – Material-UI, Ant-Design, and TailwindCss

**#Timeframe**: 36 hours

**#Path to Implementation**: Create a new 'footer.jsx' file within the 'home' folder to initiate.

> Design link is provided in Documentation below the repository 

Feel free to claim the issue in the comment section

**Comment by WadadParker** [comment]
claim

**Comment by ShauryaJain03** [comment]
claim

**Comment by shashankpatil28** [comment]
@ShauryaJain03 The current issue has been claimed by another contributor. More tasks are in the line. Stay tuned for upcoming opportunities.

**Comment by Tulsi5990** [comment]
claim
