### ISSUE TITLE
Crafting the Sign-up Component for Hitch

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#2]
# Develop the sign-up page for Hitch
Develop the sign-in component for Hitch, a vital element of our collaborative platform. Contributors are tasked with creating a user-friendly component that includes distinct fields for:
```
Name
Email Address
Username
Password
```
These fields are essential for a seamless and secure registration process. Implement robust input validation for email formats and password strength to ensure security and usability. Ensure compatibility with various devices and browsers to guarantee a consistent experience for all users.

Once completed, submit a pull request with the code, and include relevant documentation for integration.

#### Note : The sign-up route is made in app/auth/sign-in, kindly follow the same.

Time: 48 hours.

Please comment to claim the issue.

**Comment by PranavBansal21** [comment]
claim

**Comment by akshayw1** [comment]
@harshsingh554 Please make sure you are register on geekhaven events portal and devfolio

**Comment by shrutikarathi6** [comment]
claim

**Comment by shashankpatil28** [comment]
@PranavBansal21 and @shrutikarathi6 issue is already claimed. we will be having more issue on the project later. stay tuned

**Comment by shashankpatil28** [comment]
@harshsingh554 you may add antdesign and Material-UI documentation for the respective issue.

**Comment by captainflatbelly** [comment]
> @harshsingh554 Please make sure you are register on geekhaven events portal and devfolio

please add the design references for the project

**Comment by akshayw1** [comment]
@harshsingh554   Please Check its added the theme should be consistent

**Comment by Tulsi5990** [comment]
claim

**Comment by akshayw1** [comment]
@harshsingh554 Kindly Update the work you have done on issue on discord,If any help required or doubts, Please ping on discord.

**Comment by rnavaneeth992** [comment]
> @harshsingh554 Kindly Update the work you have done on issue on discord,If any help required or doubts, Please ping on discord.

Sure I will update

**Comment by rnavaneeth992** [comment]
claim
