### ISSUE TITLE
Crafting the Sign-In Component for Hitch 

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#3]
# Develop Sign-In component for Hitch
Develop the sign-in component for Hitch, a pivotal aspect of our collaborative platform.Craft a user-friendly component that seamlessly integrates a sign-in mechanism. This component should include the following distinct fields:
```
Username or Email
Password
```
These fields are essential for a seamless and secure registration process. Implement robust input validation for email formats and password strength to ensure security and usability.

Additionally, contributors should focus on responsive design, ensuring compatibility with various devices and browsers to guarantee a consistent experience for all users.

Once completed, submit a pull request with the code, and include relevant documentation for integration.
Time: 48 hours.

#### Note : The sign-in route is made in app/auth/sign-in, kindly follow the same.

Please comment to claim the issue.

**Comment by Harshal5167** [comment]
claim

**Comment by shashankpatil28** [comment]
@Harshal5167 you may refer to the Antdesign and Material-Ui documentation for styling purpose in the issue.

**Comment by Aryan4884** [comment]
claim

**Comment by Harshal5167** [comment]
@shashankpatil28 i have unassigned this issue

**Comment by rnavaneeth992** [comment]
claim

**Comment by Rohit-110** [comment]
@akshayw1  claim

**Comment by akshayw1** [comment]
@rnavaneeth992, Kindly refer to figma design, for reference and use the ease of material ui, tailwind, ant design, In order to develop it, For any doubt or help, feel free to ping on discord on our channel

**Comment by akshayw1** [comment]
@Rohit-110, Issue are claimed on Fcfs, basis, no worries will be having great issues coming up, Happy Contributing!
