### ISSUE TITLE
Dev Extravaganza: Crafting the WorkSpaceCard Component

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#34]
Hello Hitch Wizards! 🚀

We're thrilled to introduce the WorkSpaceCard component to elevate the visual appeal of Hitch. The Figma design is ready, and we can't wait to see your creative touch bring it to life!

Figma Link :
 ```https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=deTpEuaeJRzIlEK4-0```

### Tasks:

1. **Figma Design Implementation:**
   - Transform the provided Figma design for the WorkSpaceCard into a captivating and pixel-perfect React component.

2. **Styling Brilliance:**
   - Apply styles with finesse, ensuring a harmonious blend with the overall Hitch design language.

3. **Reusability Magic:**
   - Craft the WorkSpaceCard to be versatile and easily reusable across various sections of the platform.

- **Responsive Charm:**
  - Ensure the WorkSpaceCard adapts seamlessly to different screen sizes.

### Testing Invited:

- Rigorously test the component to guarantee flawless rendering and responsiveness.

### Timeframe: 
72 hours.

Hitch maestros, let's make the WorkSpaceCard a visual delight in the world of Hitch! Your creativity is what makes our platform truly special. 🌈

**Comment by rakib00-dev** [comment]
hello, I want to work on this idea but I want to build this without using any framework. the language I want to use is,  HTML, CSS, and JavaScript

**Comment by ShauryaJain03** [comment]
Claim

**Comment by rakib00-dev** [comment]
So, can I contribute it!? 🙂

**Comment by akshayw1** [comment]
@rakib00-dev , Please refer to resources on discord and as you this techstack, You will learn the required tailwind react in no time,
Happy contributing!

**Comment by shashankpatil28** [comment]
@ShauryaJain03 kindly go through the details of the issue properly and work accordingly. Quality work within time will be appreciated. for any query feel free to ask on Discord.

**Comment by ShauryaJain03** [comment]
@shashankpatil28 Sure, thank you!

**Comment by akshayw1** [comment]
@ShauryaJain03 Updates on issue assigned?

**Comment by chiragmalik2612** [comment]
still open? claim
