### ISSUE TITLE
Creating Workspaces Page Skeleton 

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#36]
Hello Builders! 🛠️

We're excited to embark on creating the Workspaces page for Hitch, and the blueprint is ready in Figma. Let's lay down the foundations and bring this page to life!

Figma Link : 
https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=deTpEuaeJRzIlEK4-0
### Tasks:

 - Translate the provided Figma design for the Workspaces page into a skeletal structure for the React components.

- **Component Architecture:**
   **Define the structure and hierarchy of React components needed for the Workspaces page.

**Navigation Integration:**
   - Implement seamless navigation elements for transitioning between different sections of the Workspaces page.

### Timeframe: 
72 hours.

Builders, let's lay the groundwork for the Workspaces page and set the stage for collaborative excellence in Hitch! Your coding expertise is the cornerstone of our success. 🌐

Thank you for contributing to the foundation of Hitch's collaborative journey! 🚀

**Comment by TheDivineAurora** [comment]
claim

**Comment by parimal-10** [comment]
claim

**Comment by shashankpatil28** [comment]
@TheDivineAurora kindly go through the issue details and work accordingly within time constraint. if any doubts, don't hesitate to ask on Discord.

**Comment by TheDivineAurora** [comment]
ok
