### ISSUE TITLE
Lift-Off: Implementing Hitch Landing Page

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#4]
# Hitch Landing Page
In this exciting task, we invite contributors to bring the vision to life by implementing the frontend for Hitch's landing page. The groundwork has been laid out in a captivating Figma design, and now we need your expertise to translate that design into a fully functional and visually stunning reality.

### Design to Life:

Your primary mission is to transform the intricate details of the Figma design into a dynamic and captivating frontend for Hitch's landing page.  

Link: 
```
https://www.figma.com/file/vyCC47vkwtmcoh1faTifkM/Hitch-Landing-Page?type=design&node-id=0-1&mode=design&t=K9GcAfpl7pGfrENr-0
```

### Leverage the power of Material UI, Ant Design, and Tailwind CSS, all pre-installed and ready for your creative touch.

Submit a pull request with your completed frontend, and let's make the landing page an enchanting gateway to the collaborative world of Hitch.

Time: 72 hours.

##### Note: The work should be done in new route, create folder home/page.jsx in app root folder and start working on it.

Please comment to claim the issue.

**Comment by KrishayNair** [comment]
claim

**Comment by Aryan4884** [comment]
claim
