### ISSUE TITLE
Crafting the 'Message' Component

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#64]
# Crafting the 'Message' Component

## Overview
Greetings Crafters!  We're excited to enrich the communication experience on Hitch by introducing the 'Message' component. The Figma design is your canvas, and we're looking for your brushstrokes to create a seamless and engaging messaging feature.

Figma link: https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=rObVWv2B1MNeRibJ-0

## Tasks
1. **Integration:**
   Transform the 'Message' component design from Figma into a captivating and functional React component.

2. **User-Centric Interface:**
   Craft an interface that ensures users experience smooth and intuitive messaging interactions.

## Considerations
- **Aesthetic Consistency:**
  Ensure the 'Message' component aligns cohesively with Hitch's overarching design language.

- **Responsive Ingenuity:**
  Develop a component that gracefully adapts to diverse screen sizes, providing a consistent user experience.

## Timeframe
36 hours.

Thank you for contributing to the essence of Hitch's collaborative journey! 🌐

**Comment by Nivedh-Biju** [comment]
claim

**Comment by QuantTitan** [comment]
claim

**Comment by atharva0192** [comment]
claim

**Comment by shashankpatil28** [comment]
@QuantTitan Congrats u have claimed. Kindly go through the details and do the task within the time constraint. Feel free to reach out on Discord if needed.

**Comment by shashankpatil28** [comment]
@Nivedh-Biju Kindly go through the task details and complete it within the time constraint. Use of MUI is mandatory. feel free to reach out on Discord.

**Comment by amanrubey** [comment]
Claim

**Comment by shashankpatil28** [comment]
@Nivedh-Biju Status, please. The task is simple comparatively.
