### ISSUE TITLE
Crafting the 'Chatbox' Component

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#65]
# Crafting the 'Chatbox' Component

## Overview
Hello Crafters! 🎨 Get ready to amplify the conversational experience on Hitch by crafting the 'Chatbox' component. 
Figma Link: [Chatbox Design](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=rObVWv2B1MNeRibJ-0)

## Tasks
1. **Integration Magic:**
   Transform the Figma design for the 'Chatbox' into a dynamic and visually appealing React component.

2. **User-Centric Design:**
   Sculpt an interface that ensures users enjoy a seamless and engaging chatbox experience.

## Considerations
- **Design Harmony:**
  Ensure the 'Chatbox' component aligns seamlessly with Hitch's overarching design language.

- **Responsive Brilliance:**
  Develop a component that adapts gracefully to diverse screen sizes, ensuring a consistent user experience.

## Timeframe
72 hours.

Crafters, let's bring life to Hitch's conversations with the 'Chatbox' component. Your coding prowess continues to shape Hitch's collaborative journey. 🚀✨

#### Note: Follow the folder structure for components and follow standard notion for nomenclature of components

Thank you for contributing to the vibrant essence of Hitch! 🌐

**Comment by amanrubey** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by shashankpatil28** [comment]
@amanrubey kindly give the status for the task.

**Comment by amanrubey** [comment]
> @shashankpatil28 just on the verge of working on it ( was learning tailwindcss, almost done will start the work and hopefully finish it before deadline)
