### ISSUE TITLE
Crafting the 'Dashboard': Chat, Collaborate, Conquer! 🚀

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#66]
# Crafting the 'Dashboard': Chat, Collaborate, Conquer! 🚀

## Overview
Hello Design Maestros! 🎨 Gear up to redefine Hitch's user experience by creating a dynamic 'Dashboard'. This central hub will be the heartbeat of collaborative activities—chatting, collaborating, and conquering milestones together. Figma Design: [Hitch Dashboard](https://www.figma.com/file/HOzZdZbjxuFtjKLRARlEOI/Dashboard-Hitch-Reference?type=design&node-id=0-1&mode=design&t=wKvlD0nBGEAMWvyi-0).

## Tasks
1. **Design Harmony:**
   Infuse the Figma design into a visually appealing and cohesive 'Dashboard' layout for Hitch.

2. **Collaboration Hub:**
   Envision and design the chat interface, ensuring a seamless and intuitive collaborative experience.

3. **Feature Integration:**
   Incorporate elements for workspace management, huddle sessions, and file sharing within the 'Dashboard'.

## Considerations
- **Consistent Aesthetics:**
  Ensure the 'Dashboard' maintains a cohesive look and feel with Hitch's design language.

- **User-Centric Approach:**
  Prioritize a user-friendly design, making navigation and feature accessibility seamless.

## Timeframe
72 hours.

Design Maestros, let's elevate Hitch's collaborative experience with a visually stunning and user-friendly 'Dashboard'. Your creative strokes will shape the future of collaboration on Hitch! 🌐✨

Thank you for contributing to the visual journey of Hitch! 🚀

#### Note : No need to claim the issue, best PR will get merged

**Comment by anshuman-rai-27** [comment]
Claim

**Comment by akshayw1** [comment]
No need to claim the issue, best PR will get merged

**Comment by Rohit-110** [comment]
c

**Comment by Nandinig24** [comment]
deadline?

**Comment by akshayw1** [comment]
Is anyone presently working on this issue

**Comment by LifeAsDev** [comment]
I will

**Comment by kushal7201** [comment]
@akshayw1 I'm working on the issue.

**Comment by akshayw1** [comment]
@kushal7201 @LifeAsDev , Today 9:00 Pm will be the deadlines and all your PR will be reviewed, Ping on discord for review priorly, So I can suggest such changes if required

**Comment by Rohit-110** [comment]
@akshayw1 Can I open a pr for this task by evening
