### ISSUE TITLE
Crafting the 'Conversation Card' Component

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#86]
# Crafting the 'Conversation Card' Component

## Overview
Hello NextJs Maestros! 🎨 We're eager to enhance the visual appeal of conversations on Hitch by introducing the 'Conversation Card'. 

## Tasks
1. **Implementation:**
   Transform the provided Figma design for the 'Conversation Card' into a visually captivating and functional React component, utilizing the principles of Material-UI (Mui) and Ant Design, tailwind.

2. **User-Centric Interface:**
   Craft an intuitive and aesthetically pleasing interface that ensures a delightful user experience, staying true to the design language of both Material-UI and Ant Design.

## Design Reference
[Figma Design for Conversation Card](https://www.figma.com/file/2hWXrRCZrGqLIUXyauG4A3/Hitch?type=design&node-id=0-1&mode=design&t=gTNsPPuSTJsEi4tQ-0)

## Considerations
- **Aesthetic Consistency:**
  Ensure the 'Conversation Card' aligns seamlessly with Hitch's overarching design language and maintains consistency with Material-UI and Ant Design principles.

- **Responsive Brilliance:**
  Develop a component that adapts gracefully to various screen sizes, providing a consistent and appealing look.

## Testing Spotlight
Rigorously test the 'Conversation Card' component to guarantee a visually stunning and user-friendly representation of discussions.

## Timeframe
72 hours.

Design Maestros, let's bring life to Hitch's conversations with the 'Conversation Card'. Your creativity, coupled with the elements of Material-UI and Ant Design, is the key to elevating the visual experience of collaborative discussions. 🌐✨

Thank you for contributing to the vibrant essence of Hitch! 🚀

**Comment by LifeAsDev** [comment]
claim

**Comment by akshayw1** [comment]
Issue are assigned on first come first serve, As you have been assigned a issue, You can start working, and Can message us on discord channel for any doubt and help needed.

**Comment by LifeAsDev** [comment]
Why you unassigned me?

**Comment by akshayw1** [comment]
Are you working on this? @LifeAsDev

**Comment by akshayw1** [comment]
Give updates regarding task on discord channel

**Comment by LifeAsDev** [comment]
I did
