### ISSUE TITLE
Connecting the Dots: Frontend and Backend API with React Query

### ISSUE THREAD

**Issue by akshayw1** [opencodeiiita/Hitch-Frontend#98]
# Implement Sign In Sign Up feature along with Hitch-Backend🧙‍♂️✨

## Overview
Greetings Wizards of Integration! 🪄🌐 We're on a quest to seamlessly integrate the magical realms of Frontend and Backend in the enchanted land of Hitch. Your mission, should you choose to accept it, is to unite the forces of sign-in and sign-up spells between the Hitch Frontend and the Backend, as detailed in the sacred scrolls of 'APIEndPoints.md'.

## Tasks
1. **Integration:**
   Weave the spells from Hitch Frontend to Backend, ensuring the flawless casting of sign-in and sign-up charms.

2. **API Endpoint Incantations:**
   Refer to the sacred scrolls in 'APIEndPoints.md' to know the exact incantations required for invoking the backend magic.

## Backend Magic Scrolls
[API Endpoint Scrolls](https://github.com/opencodeiiita/Hitch-Backend)

## Considerations
- **Magical Data Transfer:**
  Ensure the seamless transfer of magical data between the Frontend and Backend realms.

- **Error Handling Potions:**
  Brew robust error-handling potions to gracefully handle any unexpected magical disruptions.

## Testing Enchantment
Perform meticulous testing to ensure that the Frontend-Backend harmony spell works across various devices and incantations.

## Timeframe
72 magical hours.

#### Note: Use Tanstack React Query for API calls, The Sign In and Sign Up routes are documented, Use APIEndpoints.md
all API calls to be called in utils/api folder with proper naming conventions.

## React Query References
[What is React Query](https://youtu.be/novnyCaa7To?si=dHQquO8-FfbKhFqV)
[How to Use React Query](https://youtu.be/8K1N3fE-cDs?si=rNzWxdKv6c5bSQOH)

Wizards of Integration, let's unite the powers of Frontend and Backend to create a seamless and enchanting user experience in the mystical world of Hitch! 🚀✨ Your magical coding wands are the key to making this integration a legendary tale.

Thank you for contributing to the magical essence of Hitch! May your code be as unbreakable as the Elder Wand! 🪄🧙‍♂️

**Comment by rnavaneeth992** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by Karansenpai** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Sid-bit28** [comment]
claim
